Pset3
VladimirUman/JavaScript pull request #3
Opened 2018-03-21 20:38 UTC by VladimirUman

2018-03-22 14:39 UTC, AlexOrd requested changes

2018-03-22 14:39 UTC, AlexOrd commented on pset3/ps3.js
> +  var logs = now + '; Method: ' + req.method + '; Brouser: ' + req.rawHeaders[3] + ';\n'
Browser

2018-03-22 14:39 UTC, AlexOrd commented on pset3/ps3.js
> +  res.write(html);
You have to read file in additional module.

2018-03-25 08:22 UTC, VladimirUman commented on pset3/ps3.js
> +  res.write(html);
added additional module

2018-04-02 20:59 UTC, merged